### ISSUE TITLE
Can't get past "What is your cumulative ACT score"

### ISSUE THREAD

**Issue by dwertheimer** [alexa/skill-sample-nodejs-college-finder#4]
Even if I find a way around the previously reported issue (I created a new variable called TEST), I cannot get it to take my score...

>   Alexa >  To make searching easier, let's build your student profile. You can ask me to skip any of these questions if you're not sure or don't have a preference. OK. First question. You can save your SAT score or ACT score. Which one do you have?
>   User  >  ACT
>   Alexa >  Ok. What is your cumulative ACT score?
>   User  >  31
>   [Error]: Simulation did not result to an intent belonging to this skill. Please make sure the utterance text has the appropriate Alexa invocation command defined for your locale (such as "ask <invocation name>" for English locales).
>   User  >  My score was 31
>   [Error]: Simulation did not result to an intent belonging to this skill. Please make sure the utterance text has the appropriate Alexa invocation command defined for your locale (such as "ask <invocation name>" for English locales).
>   User  >  31 ACT score
>   [Error]: Simulation did not result to an intent belonging to this skill. Please make sure the utterance text has the appropriate Alexa invocation command defined for your locale (such as "ask <invocation name>" for English locales).
>   User  >  Tell college finder my ACT score was 31
>   [Error]: Simulation did not result to an intent belonging to this skill. Please make sure the utterance text has the appropriate Alexa invocation command defined for your locale (such as "ask <invocation name>" for English locales).

Turns out that the session attributes never change after that. So it won't take the number and it's basically stuck in that part of the sequence.

```
     "sessionAttributes": {
			"FIRST_RUN": false,
			"INTRO_MESSAGE": "",
			"SCORES": "ACT",
			"SKILL_STATE": "_TEST_SCORES_MODE",
			"isInitialized": true
		},
```

Thoughts?

**Comment by sharpstef** [comment]
The updated language models were missing from the models folder. I've added them now.
